<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>

        <RootNamespace>Oxide.Ext.GizmosExt</RootNamespace>
        <AssemblyName Condition="'$(RustFramework)' == 'carbon'">Carbon.Ext.GizmosExt</AssemblyName>
        <AssemblyName Condition="'$(RustFramework)' != 'carbon'">Oxide.Ext.GizmosExt</AssemblyName>

        <!-- Removes the .pdb file from the output folder. -->
        <DebugType>embedded</DebugType>
    </PropertyGroup>
</Project>
